# docker-compose.yml

version: '3'
#networks:
#  web-crawler-net:  # Container들의 Private Network을 설정한다.
#    driver: bridge
volumes:  # Container 들에서 사용되는 Volume을 정의한다.
    siiot-chat-cache-volume: {}
#    web-crawler-task-volume: {}
services:
    siiot-chat-cache:
        image: redis:5.0.3-alpine
        command: redis-server
        ports:
            - "6379:6379"
        volumes:
            - siiot-chat-cache-volume:/data
        healthcheck:
            test: "redis-cli -h 127.0.0.1 ping"
            interval: 3s
            timeout: 1s
            retries: 5
#        networks:
#          - web-crawler-net
    siiot-chat:
        image: siiot-chat-server_siiot-chat:0.0.4
#        build:
#            context: .
#            dockerfile: ./Dockerfile
        ports:
            - "0.0.0.0:8001:8001"
        depends_on:
            - siiot-chat-cache
        links:
            - siiot-chat-cache:web-crawler-cache
        command: python manage.py runserver 0.0.0.0:8001
        volumes:
            - .:/siiot-chat/siiot-chat
#            - web-crawler-task-volume:/web-crawler/web-crawler-task:Z
#        networks:
#          - web-crawler-net
#    web-crawler-task:
#        image: monde-bengal_web-crawler:0.2.2
#        build:
#            context: .
#            dockerfile: ./Dockerfile
#        depends_on:
#            - web-crawler-cache
#        links:
#            - web-crawler-cache:web-crawler-cache
#        command: celery -A web_crawler worker -l info
#        volumes:
#            - .:/web-crawler/web-crawler
#            - web-crawler-task-volume:/web-crawler/web-crawler-task:Z
#        networks:
#          - web-crawler-net